export const themes = {
    default: {
      background: "white",
      text: "#333",
      primary: "black",
      buttonText: "white",
      headerBackground: "#f1f8ff",
      activeStrokeColor: "#00e676",
      inactiveStrokeColor: "#bcbcbc",
      sectionBackground: "white",
      disabledButtonBackground: "grey",
      accent1: "royalblue",
      navButtonColor: "blue",
    },
    dark: {
      background: "#121212",
      text: "#E0E0E0",
      primary: "#333333",
      buttonText: "#FFFFFF",
      headerBackground: "#333333",
      activeStrokeColor: "#BB86FC",
      inactiveStrokeColor: "#3E3E3E",
      sectionBackground: "#222222",
      disabledButtonBackground: "#525252",
      accent1: "#6200EE",
      navButtonColor: "#BB86FC",
    },
    light: {
      background: "#F0F0F0",
      text: "#333",
      primary: "#FFFFFF",
      buttonText: "black",
      headerBackground: "#FFFFFF",
      activeStrokeColor: "#4CAF50",
      inactiveStrokeColor: "#CCCCCC",
      sectionBackground: "white",
      disabledButtonBackground: "#CCCCCC",
      accent1: "#03A9F4",
      navButtonColor: "blue",
    },
    oceanic: {
      background: "#e0f7fa",
      text: "#01579b",
      primary: "#00bcd4",
      buttonText: "#ffffff",
      headerBackground: "#b3e5fc",
      activeStrokeColor: "#4dd0e1",
      inactiveStrokeColor: "#b2ebf2",
      sectionBackground: "#e1f5fe",
      disabledButtonBackground: "#b0bec5",
      accent1: "#0288d1",
      navButtonColor: "#0277bd",
    },
    forest: {
      background: "#e8f5e9",
      text: "#1b5e20",
      primary: "#4caf50",
      buttonText: "#ffffff",
      headerBackground: "#c8e6c9",
      activeStrokeColor: "#81c784",
      inactiveStrokeColor: "#a5d6a7",
      sectionBackground: "#dcedc8",
      disabledButtonBackground: "#aebfbe",
      accent1: "#388e3c",
      navButtonColor: "#2e7d32",
    },
    neon: {
      background: "#f4f4f4",
      text: "#212121",
      primary: "#ff4081",
      buttonText: "#ffffff",
      headerBackground: "#f8bbd0",
      activeStrokeColor: "#f50057",
      inactiveStrokeColor: "#ff80ab",
      sectionBackground: "#fce4ec",
      disabledButtonBackground: "#f8bbd0",
      accent1: "#ff5252",
      navButtonColor: "#d81b60",
    }
  };
  
  export default themes;